name: Scheduled Workflow

on:
  schedule:
    - cron: "0/5 * * * *"
  #push:
   # branches:
   #   - develop

jobs:
   k6_load_test:
     name: k6 Load Test
     runs-on: ubuntu-latest
     steps:
     - name: Checkout
       uses: actions/checkout@v1
     - name: Run local k6 test
       uses: k6io/action@v0.1
       with:
         filename: test.js     
     - name: Send a Slack Notification
       uses: 8398a7/action-slack@v3
       with:
         channel: '#gintaa-github'
         status: custom
         fields: repo,message,commit,author,action,eventName,ref,workflow # selectable (default: repo,message)
         custom_payload: |
          {
             username: 'action-slack',
             icon_emoji: ':octocat:',
             attachments: [{
               color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
               text: 'Microservices successfully published in GCR',
             }]
            }
       env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # optional
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
